[versions]
detekt = "1.21.0-RC2"
kotlin = "1.7.10"
graphql = "5.3.2"

commons-text = "1.9"
excelkt = "1.0.2"
groovy = "3.0.9"
homoglyph = "1.1.1"
jansi = "2.4.0"
jsoup = "1.15.2"
kaml = "0.43.0"
kmongo = "4.5.1"
kordex = "1.5.5-SNAPSHOT"
kx-ser = "1.3.3"
logback = "1.2.5"
logging = "2.1.23"
rgxgen = "1.3"
semver = "1.3.0"

[libraries]
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
excelkt = { module = "io.github.evanrupert:excelkt", version.ref = "excelkt" }
graphql = { module = "com.expediagroup:graphql-kotlin-ktor-client", version.ref = "graphql" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
homoglyph = { module = "net.codebox:homoglyph", version.ref = "homoglyph" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kmongo = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }
kordex-annotations = { module = "com.kotlindiscord.kord.extensions:annotations", version.ref = "kordex" }
kordex-annotationProcessor = { module = "com.kotlindiscord.kord.extensions:annotation-processor", version.ref = "kordex" }
kordex-core = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kordex" }
kordex-mappings = { module = "com.kotlindiscord.kord.extensions:extra-mappings", version.ref = "kordex" }
kordex-phishing = { module = "com.kotlindiscord.kord.extensions:extra-phishing", version.ref = "kordex" }
kordex-pluralkit = { module = "com.kotlindiscord.kord.extensions:extra-pluralkit", version.ref = "kordex" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
rgxgen = { module = "com.github.curious-odd-man:rgxgen", version.ref = "rgxgen" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
